add list and one meme view
meme-soft/meme-saver pull request #8
Opened 2020-11-24 18:29 UTC by kirillzykov

2020-11-24 18:57 UTC, mikitachab requested changes

2020-11-24 18:57 UTC, mikitachab commented on client/package.json
> +    "@types/react-router-dom": "^5.1.6",
move to dev deps

2020-11-24 18:57 UTC, mikitachab commented on client/package.json
> +    "lint": "eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=1 --fix"
rm --fix
create separate separate script with --fix option

2020-11-24 18:57 UTC, mikitachab commented on client/src/App.tsx
> +import 'bootstrap/dist/css/bootstrap.min.css';
why we need this here?

2020-11-24 18:57 UTC, mikitachab commented on client/src/components/Meme.tsx
> +  //    date: Date,
why commented?

2020-11-24 18:57 UTC, mikitachab commented on client/src/components/MemeLI.tsx
> +  //    description: string,
delete or uncomment

2020-11-24 18:57 UTC, mikitachab commented on client/src/components/MemeList.tsx
> +/* eslint no-underscore-dangle: 0 */
?

2020-11-24 19:05 UTC, mikitachab commented on client/src/components/MemeList.tsx
> +interface IMeme{
there is too many similar "Meme" types

2020-11-25 09:20 UTC, mikitachab requested changes

2020-11-25 09:20 UTC, mikitachab commented on server/src/server.ts
> +app.use('/api/v1/memes/', allMemesRouter);
why we need separate router for every handler?

2020-11-25 09:24 UTC, mikitachab commented on client/src/components/MemeList.tsx
> +              <MemeLI
this should be done in a way similar to:
```jsx
memes.map((meme, i) => (
<MemeLI
    meme={meme}
    onClick={clickHandler}
    key={i}
/>)
```

2020-11-26 21:16 UTC, mikitachab requested changes

2020-11-26 21:16 UTC, mikitachab commented on client/src/types/meme.interface.ts
> +export default interface IMeme{
:+1:

2020-11-26 21:16 UTC, mikitachab commented on server/src/server.ts
> +//  app.use('/api/v1/memes/', allMemesRouter);
rm

2020-11-27 19:12 UTC, mikitachab approved these changes

2020-12-03 09:38 UTC, W2MANE approved these changes

2020-12-03 10:30 UTC, merged